version: 1.0.1.{build}

# clone directory
clone_folder: c:\projects\rogueloader

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: Rogueloader.sln
  verbosity: normal

# scripts to run after build
before_build:
  - nuget restore
after_build:
  - cd c:\projects\rogueloader
  - copy c:\projects\rogueloader\DarkLoader\bin\Release\RogueLoader.exe c:\projects\rogueloader\RogueLoader.exe
artifacts:
  - path: RogueLoader.exe
    name: RogueLoader.exe

